version: '3'

volumes:
  traefik-acme:
    driver: local

services:
  traefik-init:
    image: alpine
    command: sh -c "mkdir -p /letsencrypt && touch /letsencrypt/acme.json && chmod 600 /letsencrypt/acme.json"
    volumes:
      - traefik-acme:/letsencrypt

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - traefik-init
    security_opt:
      - no-new-privileges:true
    ports:
      - "195.15.240.76:80:80"
      - "195.15.240.76:443:443"
      - "195.15.240.76:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme:/letsencrypt:rw
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Dashboard configuration
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.dockersphere.ovh`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$O7TOR0Eq$$uqqmZk/Dh4FxjDE7dd1yA0"
      - "traefik.http.routers.dashboard.middlewares=auth"
      # HTTPS redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # NextJS Application configuration
      - "traefik.http.routers.nextapp.rule=Host(`dockersphere.ovh`)"
      - "traefik.http.routers.nextapp.entrypoints=websecure"
      - "traefik.http.routers.nextapp.tls=true"
      - "traefik.http.routers.nextapp.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nextapp.service=nextapp-service"
      - "traefik.http.services.nextapp-service.loadbalancer.server.port=3000"
      - "traefik.http.services.nextapp-service.loadbalancer.servers[0].url=http://195.15.240.76:3000"
    command:
      - --api.dashboard=true
      - --log.level=DEBUG
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=dynastie.amoussou.etu@gmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=proxy

networks:
  proxy:
    external: true
