version: "3.8"

services:

  mongodb1:
    image: public.ecr.aws/alanedwardes/mongodb-without-avx:6.0.5
    hostname: mongodb1
    container_name: mongodb1
    cpus: "1"
    mem_limit: 2g
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data1:/data/db
      - ./init_replica.sh:/docker-entrypoint-initdb.d/init_replica.sh
      - ./init-replset.js:/docker-entrypoint-initdb.d/init-replset.js
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.initiate({_id:'rs0',members:[{_id:0,host:'mongodb1:27017'},{_id:1,host:'mongodb2:27017'},{_id:2,host:'mongodb3:27017'}]})"]
      interval: 5s
      timeout: 30s
      start_period: 30s
      retries: 10
    restart: always
    ports:
      - 27017:27017

  mongodb2:
    image: public.ecr.aws/alanedwardes/mongodb-without-avx:6.0.5
    hostname: mongodb2
    container_name: mongodb2
    cpus: "1"
    mem_limit: 2g
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data2:/data/db
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - proxy
    restart: always
    ports:
      - 27018:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status().ok"]
      interval: 5s
      timeout: 30s
      start_period: 30s
      retries: 10

  mongodb3:
    image: public.ecr.aws/alanedwardes/mongodb-without-avx:6.0.5
    hostname: mongodb3
    container_name: mongodb3
    cpus: "1"
    mem_limit: 2g
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data3:/data/db
      - ./mongod.conf:/etc/mongod.conf
    networks:
      - proxy
    restart: always
    ports:
      - 27019:27017
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status().ok"]
      interval: 5s
      timeout: 30s
      start_period: 30s
      retries: 10

volumes:

  mongo_data1:
    driver: local
    name: mongo_data1

  mongo_data2:
    driver: local
    name: mongo_data2

  mongo_data3:
    driver: local
    name: mongo_data3

networks:
  proxy:
    external: true
